///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyWebVIPTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddVIPs recording.
    /// </summary>
    [TestModule("6621484a-98b3-469f-8c10-c29df26737b7", ModuleType.Recording, 1)]
    public partial class AddVIPs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyWebVIPTestRepository repository.
        /// </summary>
        public static MyWebVIPTestRepository repo = MyWebVIPTestRepository.Instance;

        static AddVIPs instance = new AddVIPs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddVIPs()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddVIPs Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            MyCustomClickAndType(repo.RanorexVIPDatabaseTestWebApplicatio.InputFields_SimpleFolder.FirstName, "Jay");
            Delay.Milliseconds(0);
            
            MyCustomClickAndType(repo.RanorexVIPDatabaseTestWebApplicatio.InputFields_SimpleFolder.LastName, "Branham");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.Category_RootedFolder.Other' at 19;6.", repo.RanorexVIPDatabaseTestWebApplicatio.Category_RootedFolder.OtherInfo, new RecordItemIndex(2));
            repo.RanorexVIPDatabaseTestWebApplicatio.Category_RootedFolder.Other.Click("19;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.RadioButtons_RootedFolder.Male' at 5;7.", repo.RanorexVIPDatabaseTestWebApplicatio.RadioButtons_RootedFolder.MaleInfo, new RecordItemIndex(3));
            repo.RanorexVIPDatabaseTestWebApplicatio.RadioButtons_RootedFolder.Male.Click("5;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.InputTagAdd' at 25;12.", repo.RanorexVIPDatabaseTestWebApplicatio.InputTagAddInfo, new RecordItemIndex(4));
            repo.RanorexVIPDatabaseTestWebApplicatio.InputTagAdd.Click("25;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='VIP count: 1') on item 'RanorexVIPDatabaseTestWebApplicatio.Count'.", repo.RanorexVIPDatabaseTestWebApplicatio.CountInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.RanorexVIPDatabaseTestWebApplicatio.CountInfo, "InnerText", "VIP count: 1");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
